#Changing settings here have no effect.  Please copy and paste this into ~/.siriproxy to make the configurations work.

- name: 'Automation'
  git: 'https://github.com/fabianorosa1/siriproxy-automation.git'

#Then update with 'rvmsudo siriproxy bundle'